safe:        false
auto:        false
server:      false
server_port: 4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    liquid
permalink:   /:categories/:title

title:         Wickerbox
description:   World travel photos, airplanes, avionics, rockets, robots, linux, and two cats.
base:          http://www.wickerbox.net/
author:        Jen 'wicker' Hanni
email:         jeh.wicker@gmail.com

disqus_id:     wickerbox
