safe:        false
auto:        false
server:      false
server_port: 4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    engine
permalink:   /:categories/:title
paginate:    20
#limit_posts: 20

title:         compendiarious
description:   engineering student blog
base:          http://www.compendiarious.net/
author:        Jen Hanni
email:         jeh.wicker@gmail.com

disqus_id:     compendiarious

exclude: ["images"]
